[package]
name = "clasp-core-fuzz"
version = "0.0.0"
authors = ["LumenCanvas"]
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
bytes = "1.5"

[dependencies.clasp-core]
path = ".."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[profile.release]
debug = 1

[[bin]]
name = "fuzz_decode_frame"
path = "fuzz_targets/fuzz_decode_frame.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_decode_message"
path = "fuzz_targets/fuzz_decode_message.rs"
test = false
doc = false
bench = false
